sudo: yes
dist: bionic
language: python

python:
- '3.6'

branches:
  only:
  - master

services:
  - postgresql

install:
- pip install tox-travis
before_script:
- psql -c "CREATE USER payg WITH PASSWORD 'payg_service';"
- createdb payg_service_test -O payg -T template0

script:
- python -m unittest tests/test.py

# deploy:
# - provider: script
#   script: bash scripts/deploy.sh dev aws-dev
#   on:
#     branch: master
#     python: 3.7